---
- name: Install Apache, set timezone, display custom HTML page on My Hostname
  hosts: all
  become: yes
  remote_user: ubuntu

  tasks:
    - name: Install Apache
        apt: name=apache2 update_cache=yes state=present
    
    - name: Set timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos
      register: set_timezone_result
      ignore_errors: yes
    
    - name: Get instance timezone
      shell: echo $(timedatectl | grep "Time zone")
      register: timezone
      
    - name: print hostname
      tags: printf
      shell: echo "<h1>THE HOSTNAME OF MY SYSTEM IS $(hostname -f)</h1>" > /var/www/html/index.html

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted